In [1]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\marye\anaconda3\lib\site-packages (1.0.2)
Collecting scikit-learn
  Downloading scikit_learn-1.2.1-cp39-cp39-win_amd64.whl (8.4 MB)
     ---------------------------------------- 8.4/8.4 MB 381.1 kB/s eta 0:00:00
Collecting joblib>=1.1.1
  Downloading joblib-1.2.0-py3-none-any.whl (297 kB)
     ------------------------------------ 298.0/298.0 kB 428.2 kB/s eta 0:00:00
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\marye\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: scipy>=1.3.2 in c:\users\marye\anaconda3\lib\site-packages (from scikit-learn) (1.9.1)
Requirement already satisfied: numpy>=1.17.3 in c:\users\marye\anaconda3\lib\site-packages (from scikit-learn) (1.21.5)
Installing collected packages: joblib, scikit-learn
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.0.2
    Uninstalling scikit-learn-1.0.2:
      Successfully uninstalled scikit-learn-1.0.2
Successfully installed joblib-1.2.0 scikit-learn-1.2.1

In [2]:
!pip install GEOparse

Collecting GEOparse
  Downloading GEOparse-2.0.3.tar.gz (278 kB)
     ------------------------------------ 278.5/278.5 kB 464.1 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: numpy>=1.7 in c:\users\marye\anaconda3\lib\site-packages (from GEOparse) (1.21.5)
Requirement already satisfied: pandas>=0.17 in c:\users\marye\anaconda3\lib\site-packages (from GEOparse) (1.4.4)
Requirement already satisfied: requests>=2.21.0 in c:\users\marye\anaconda3\lib\site-packages (from GEOparse) (2.28.1)
Requirement already satisfied: tqdm>=4.31.1 in c:\users\marye\anaconda3\lib\site-packages (from GEOparse) (4.64.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\marye\anaconda3\lib\site-packages (from pandas>=0.17->GEOparse) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\marye\anaconda3\lib\site-packages (from pandas>=0.17->GEOparse) (2022.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\marye\anaconda3\lib\site-packages (from requests>=2.21.0->GEOparse) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\marye\anaconda3\lib\site-packages (from requests>=2.21.0->GEOparse) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marye\anaconda3\lib\site-packages (from requests>=2.21.0->GEOparse) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\marye\anaconda3\lib\site-packages (from requests>=2.21.0->GEOparse) (2022.9.14)
Requirement already satisfied: colorama in c:\users\marye\anaconda3\lib\site-packages (from tqdm>=4.31.1->GEOparse) (0.4.5)
Requirement already satisfied: six>=1.5 in c:\users\marye\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=0.17->GEOparse) (1.16.0)
Building wheels for collected packages: GEOparse
  Building wheel for GEOparse (setup.py): started
  Building wheel for GEOparse (setup.py): finished with status 'done'
  Created wheel for GEOparse: filename=GEOparse-2.0.3-py3-none-any.whl size=29065 sha256=c528a1c57507fcc818dcffccb4d14a413f8057b62290bbfe628f2b653efdd8a8
  Stored in directory: c:\users\marye\appdata\local\pip\cache\wheels\b4\27\3b\3faf8423d9c4fad02d693b4d75d1b6e82fde1d5cf59cc9a40e
Successfully built GEOparse
Installing collected packages: GEOparse
Successfully installed GEOparse-2.0.3

In [43]:
import numpy as np 
import pandas as pd
dataset = pd.read_csv("dataIWithTargetValues-txt.csv")
#dataset2 = pd.read_csv("dataII.csv")

In [44]:
df

,"""GSM74239""","""GSM74240""","""GSM74241""","""GSM74242""","""GSM74243""","""GSM74244""","""GSM74245""","""GSM74246""","""GSM74247""","""GSM74248""",...,"""GSM121391""","""GSM121392""","""GSM121393""","""GSM121394""","""GSM121395""","""GSM121396""","""GSM121397""","""GSM121398""","""GSM121399""","""GSM121407"""
1,53.7452507019043,398.217529296875,476.876739501953,285.281463623047,418.731475830078,308.545440673828,205.691345214844,400.727661132812,186.328323364258,309.432556152344,...,530.799926757812,430.436584472656,253.215911865234,191.995513916016,377.195739746094,400.810791015625,236.318222045898,210.678695678711,176.634094238281,159.44287109375
2,483.366943359375,318.69580078125,233.067993164062,377.694519042969,336.891204833984,305.663177490234,277.269165039062,322.180786132812,300.988677978516,351.027740478516,...,327.981384277344,422.289764404297,185.197570800781,413.729187011719,326.87841796875,356.851776123047,272.176849365234,219.225784301758,224.363571166992,435.373107910156
3,3044.49267578125,3614.12182617188,2816.37841796875,2772.38403320312,3105.17700195312,3346.9716796875,2559.171875,3803.66333007812,3449.0029296875,3723.65283203125,...,2811.51928710938,2423.49829101562,3079.16333007812,2272.43579101562,2984.95825195312,3003.22338867188,2283.87036132812,2240.99291992188,2219.3681640625,2624.15161132812
4,207.656005859375,152.559188842773,99.692138671875,133.170013427734,176.241088867188,116.961730957031,155.374145507812,127.237594604492,98.381233215332,186.740036010742,...,137.158889770508,233.025253295898,179.992584228516,106.888854980469,113.386901855469,147.968765258789,113.717994689941,88.0371780395508,82.6059875488281,131.276306152344
5,1056.7705078125,865.037780761719,653.934692382812,675.938415527344,701.24560546875,530.420776367188,649.928344726562,570.953002929688,538.835388183594,681.028503417969,...,1171.03869628906,1540.43286132812,2789.40942382812,984.302062988281,994.017395019531,905.220153808594,1028.5625,910.9931640625,1711.20739746094,554.348205566406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22279,109.582931518555,147.647933959961,33.9032745361328,79.7916870117188,104.297271728516,26.251880645752,120.899795532227,110.567802429199,39.8069801330566,86.4826507568359,...,43.2015724182129,42.5648155212402,95.1865310668945,62.6825332641602,63.7643051147461,81.7485198974609,50.7704696655273,37.6312408447266,36.2432670593262,14.4145307540894
22280,32.877571105957,14.4215307235718,6.36603403091431,47.8829078674316,37.9879570007324,10.5922269821167,10.2377920150757,6.90692281723022,8.39138317108154,5.22587251663208,...,34.6311531066895,11.7137250900269,88.5610733032227,2.94605016708374,6.79386425018311,5.61661672592163,19.0337028503418,7.43142747879028,9.87153816223145,6.24741888046265
22281,34.0942687988281,32.8462257385254,29.4277782440186,19.107120513916,21.7523193359375,17.6396331787109,17.2233505249023,18.7971572875977,18.7260341644287,57.6825370788574,...,12.795506477356,29.9239444732666,154.129364013672,40.2984161376953,75.4655609130859,91.7178421020508,50.1546783447266,5.09233999252319,49.6119155883789,13.400990486145
22282,35.3568077087402,22.4525661468506,10.9492521286011,10.4670381546021,11.8251085281372,12.1172790527344,12.7682723999023,12.1748352050781,13.3672523498535,15.4648742675781,...,13.8584766387939,16.9302806854248,19.6987724304199,8.89613914489746,9.60581016540527,10.4983520507812,6.1165509223938,10.6974248886108,11.166467666626,7.56165027618408
22283,BMD,ALS,ALS,ALS,ALS,ALS,ALS,ALS,ALS,ALS,...,JDM,JDM,JDM,JDM,JDM,JDM,JDM,JDM,JDM,FSHD

In [45]:
for i in range(0,22284):
    for j in range(0,122):
        s=dataset.iloc[i,j]
        
        dataset.iloc[i,j]=s[1:-1]

In [48]:
df=dataset.T

In [52]:
dfX

,0,1,2,3,4,5,6,7,8,9,...,22274,22275,22276,22277,22278,22279,22280,22281,22282,22283
"""GSM74239""",1565.09008789062,53.7452507019043,483.366943359375,3044.49267578125,207.656005859375,1056.7705078125,354.069854736328,308.298919677734,155.997940063477,75.7416687011719,...,466.054229736328,59558.76171875,61949.91015625,59.3553199768066,36.8796081542969,109.582931518555,32.877571105957,34.0942687988281,35.3568077087402,BMD
"""GSM74240""",1793.82397460938,398.217529296875,318.69580078125,3614.12182617188,152.559188842773,865.037780761719,503.007385253906,105.136489868164,48.6479034423828,137.83952331543,...,343.9833984375,6001.11083984375,8947.3623046875,38.0662994384766,52.5047416687012,147.647933959961,14.4215307235718,32.8462257385254,22.4525661468506,ALS
"""GSM74241""",2058.33154296875,476.876739501953,233.067993164062,2816.37841796875,99.692138671875,653.934692382812,280.965087890625,251.758575439453,46.3511352539062,204.119140625,...,320.022247314453,10012.01171875,18654.59765625,26.7110958099365,18.0695552825928,33.9032745361328,6.36603403091431,29.4277782440186,10.9492521286011,ALS
"""GSM74242""",2189.998046875,285.281463623047,377.694519042969,2772.38403320312,133.170013427734,675.938415527344,366.094696044922,107.485481262207,121.23754119873,184.002349853516,...,496.929534912109,20802.712890625,20401.41015625,32.4928970336914,32.5548515319824,79.7916870117188,47.8829078674316,19.107120513916,10.4670381546021,ALS
"""GSM74243""",1900.70324707031,418.731475830078,336.891204833984,3105.17700195312,176.241088867188,701.24560546875,336.056915283203,58.0718727111816,158.303771972656,105.79239654541,...,405.852020263672,11937.9462890625,14897.8212890625,38.861442565918,26.9782028198242,104.297271728516,37.9879570007324,21.7523193359375,11.8251085281372,ALS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""GSM121396""",1693.46533203125,400.810791015625,356.851776123047,3003.22338867188,147.968765258789,905.220153808594,397.064239501953,39.9436721801758,161.248687744141,172.840560913086,...,329.838989257812,34602.6171875,28734.962890625,24.4476413726807,45.9580192565918,81.7485198974609,5.61661672592163,91.7178421020508,10.4983520507812,JDM
"""GSM121397""",2706.814453125,236.318222045898,272.176849365234,2283.87036132812,113.717994689941,1028.5625,334.782775878906,103.489768981934,429.438171386719,161.858306884766,...,109.378257751465,19557.150390625,15422.4951171875,12.0567960739136,14.94508934021,50.7704696655273,19.0337028503418,50.1546783447266,6.1165509223938,JDM
"""GSM121398""",1790.87670898438,210.678695678711,219.225784301758,2240.99291992188,88.0371780395508,910.9931640625,341.301422119141,293.70947265625,501.354888916016,120.607307434082,...,175.606842041016,19784.10546875,16721.51953125,14.2686529159546,11.1277942657471,37.6312408447266,7.43142747879028,5.09233999252319,10.6974248886108,JDM
"""GSM121399""",1854.69946289062,176.634094238281,224.363571166992,2219.3681640625,82.6059875488281,1711.20739746094,442.881408691406,336.195465087891,479.007781982422,86.310920715332,...,293.994323730469,24775.755859375,16098.21484375,22.118444442749,24.3609809875488,36.2432670593262,9.87153816223145,49.6119155883789,11.166467666626,JDM
"""GSM121407""",2254.56396484375,159.44287109375,435.373107910156,2624.15161132812,131.276306152344,554.348205566406,368.054809570312,339.686920166016,28.5210971832275,89.1872711181641,...,317.549407958984,24119.9375,22249.279296875,12.3076810836792,8.7567777633667,14.4145307540894,6.24741888046265,13.400990486145,7.56165027618408,FSHD

In [86]:
dfX=df.iloc[1:,:]

In [89]:
dfX.iloc[1:,:]

,0,1,2,3,4,5,6,7,8,9,...,22274,22275,22276,22277,22278,22279,22280,22281,22282,22283
"""GSM74240""",1793.82397460938,398.217529296875,318.69580078125,3614.12182617188,152.559188842773,865.037780761719,503.007385253906,105.136489868164,48.6479034423828,137.83952331543,...,343.9833984375,6001.11083984375,8947.3623046875,38.0662994384766,52.5047416687012,147.647933959961,14.4215307235718,32.8462257385254,22.4525661468506,ALS
"""GSM74241""",2058.33154296875,476.876739501953,233.067993164062,2816.37841796875,99.692138671875,653.934692382812,280.965087890625,251.758575439453,46.3511352539062,204.119140625,...,320.022247314453,10012.01171875,18654.59765625,26.7110958099365,18.0695552825928,33.9032745361328,6.36603403091431,29.4277782440186,10.9492521286011,ALS
"""GSM74242""",2189.998046875,285.281463623047,377.694519042969,2772.38403320312,133.170013427734,675.938415527344,366.094696044922,107.485481262207,121.23754119873,184.002349853516,...,496.929534912109,20802.712890625,20401.41015625,32.4928970336914,32.5548515319824,79.7916870117188,47.8829078674316,19.107120513916,10.4670381546021,ALS
"""GSM74243""",1900.70324707031,418.731475830078,336.891204833984,3105.17700195312,176.241088867188,701.24560546875,336.056915283203,58.0718727111816,158.303771972656,105.79239654541,...,405.852020263672,11937.9462890625,14897.8212890625,38.861442565918,26.9782028198242,104.297271728516,37.9879570007324,21.7523193359375,11.8251085281372,ALS
"""GSM74244""",1986.62121582031,308.545440673828,305.663177490234,3346.9716796875,116.961730957031,530.420776367188,449.625091552734,76.1387252807617,31.5945053100586,156.005844116211,...,380.112731933594,8748.185546875,11304.060546875,17.7410717010498,30.6585826873779,26.251880645752,10.5922269821167,17.6396331787109,12.1172790527344,ALS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"""GSM121396""",1693.46533203125,400.810791015625,356.851776123047,3003.22338867188,147.968765258789,905.220153808594,397.064239501953,39.9436721801758,161.248687744141,172.840560913086,...,329.838989257812,34602.6171875,28734.962890625,24.4476413726807,45.9580192565918,81.7485198974609,5.61661672592163,91.7178421020508,10.4983520507812,JDM
"""GSM121397""",2706.814453125,236.318222045898,272.176849365234,2283.87036132812,113.717994689941,1028.5625,334.782775878906,103.489768981934,429.438171386719,161.858306884766,...,109.378257751465,19557.150390625,15422.4951171875,12.0567960739136,14.94508934021,50.7704696655273,19.0337028503418,50.1546783447266,6.1165509223938,JDM
"""GSM121398""",1790.87670898438,210.678695678711,219.225784301758,2240.99291992188,88.0371780395508,910.9931640625,341.301422119141,293.70947265625,501.354888916016,120.607307434082,...,175.606842041016,19784.10546875,16721.51953125,14.2686529159546,11.1277942657471,37.6312408447266,7.43142747879028,5.09233999252319,10.6974248886108,JDM
"""GSM121399""",1854.69946289062,176.634094238281,224.363571166992,2219.3681640625,82.6059875488281,1711.20739746094,442.881408691406,336.195465087891,479.007781982422,86.310920715332,...,293.994323730469,24775.755859375,16098.21484375,22.118444442749,24.3609809875488,36.2432670593262,9.87153816223145,49.6119155883789,11.166467666626,JDM
"""GSM121407""",2254.56396484375,159.44287109375,435.373107910156,2624.15161132812,131.276306152344,554.348205566406,368.054809570312,339.686920166016,28.5210971832275,89.1872711181641,...,317.549407958984,24119.9375,22249.279296875,12.3076810836792,8.7567777633667,14.4145307540894,6.24741888046265,13.400990486145,7.56165027618408,FSHD

In [56]:
from sklearn.model_selection import train_test_split
training_set, test_set = train_test_split(dfX, test_size = 0.2, random_state = 1)

In [100]:
X_train = training_set.iloc[:,0:22282].values
Y_train = training_set.iloc[:,22283].values
X_test = test_set.iloc[:,0:22282].values
Y_test = test_set.iloc[:,22283].values

In [101]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf', random_state = 1)
classifier.fit(X_train,Y_train)

SVC(random_state=1)

In [102]:
Y_pred = classifier.predict(X_test)

In [103]:
test_set["Predictions"] = Y_pred

In [104]:
test_set

,0,1,2,3,4,5,6,7,8,9,...,22275,22276,22277,22278,22279,22280,22281,22282,22283,Predictions
"""GSM121372""",1984.01306152344,202.490051269531,279.75048828125,3019.35668945312,70.2384567260742,538.876525878906,220.007904052734,372.681640625,85.0034713745117,196.309097290039,...,27111.640625,22565.9375,17.8218536376953,26.5718021392822,29.5940551757812,5.66834259033203,15.7735071182251,11.0399188995361,FSHD,FSHD
"""GSM74395""",2366.96655273438,305.328002929688,657.839416503906,3538.58520507812,149.940078735352,1091.60998535156,574.448608398438,303.683868408203,142.956390380859,326.220489501953,...,35012.3828125,46794.14453125,46.7492561340332,46.7034683227539,167.038009643555,9.83773612976074,154.769989013672,23.4294528961182,LGMD2I,FSHD
"""GSM74400""",2049.08325195312,298.284240722656,442.2568359375,4008.0908203125,232.528274536133,913.599914550781,506.878448486328,51.3886451721191,282.526336669922,148.922760009766,...,46570.46875,58906.99609375,179.151214599609,50.4664726257324,149.111114501953,151.666809082031,48.5132369995117,46.9104843139648,LGMD2I,LGMD2A
"""GSM121398""",1790.87670898438,210.678695678711,219.225784301758,2240.99291992188,88.0371780395508,910.9931640625,341.301422119141,293.70947265625,501.354888916016,120.607307434082,...,19784.10546875,16721.51953125,14.2686529159546,11.1277942657471,37.6312408447266,7.43142747879028,5.09233999252319,10.6974248886108,JDM,JDM
"""GSM74418""",2164.83544921875,57.8686370849609,473.548217773438,3006.1181640625,243.97590637207,916.359375,804.529052734375,108.320175170898,37.857608795166,225.63850402832,...,127677.3203125,115225.09375,48.0911102294922,33.7732467651367,130.034240722656,29.9888916015625,16.815896987915,52.2601318359375,HSP,Control
"""GSM74387""",2287.66552734375,337.606231689453,269.252166748047,2935.5361328125,180.118041992188,610.251525878906,261.639831542969,243.838073730469,89.2598190307617,197.194915771484,...,39962.73046875,33240.109375,26.2056083679199,15.2055950164795,83.9236831665039,6.2469220161438,58.7346229553223,9.8806209564209,EDMD_AD,FSHD
"""GSM74372""",2048.94384765625,303.778198242188,632.32861328125,3454.44946289062,443.856079101562,991.802124023438,481.539245605469,236.087753295898,54.1008148193359,278.003936767578,...,100304.8515625,76786.4609375,38.012996673584,25.2303943634033,231.776947021484,17.5187568664551,123.101921081543,53.6314811706543,LGMD2A,DMD
"""GSM121358""",1646.81079101562,295.649291992188,435.100067138672,2538.125,25.1534805297852,403.588165283203,378.681915283203,350.439483642578,43.4925422668457,138.242172241211,...,25106.06640625,23687.390625,19.2562942504883,27.6830081939697,47.2711448669434,27.8360023498535,20.5357074737549,11.6905651092529,FSHD,FSHD
"""GSM74389""",2568.73803710938,269.596466064453,350.002807617188,3418.72875976562,133.882354736328,648.6337890625,342.887298583984,68.911491394043,78.8220748901367,237.456405639648,...,26270.986328125,20773.705078125,27.399435043335,57.4962348937988,131.345825195312,4.68210506439209,26.6324787139893,23.9489803314209,EDMD_XR,FSHD
"""GSM121379""",1780.72619628906,324.067840576172,279.161254882812,2221.48022460938,138.671859741211,1726.74829101562,559.835754394531,176.472030639648,2056.076171875,141.684768676758,...,29370.90234375,22309.423828125,19.8710021972656,25.7768230438232,50.7673301696777,4.2703332901001,38.8526954650879,10.8118743896484,JDM,JDM
"""GSM121374""",1593.49829101562,209.768035888672,414.5478515625,4889.16162109375,264.641632080078,686.772399902344,419.281158447266,110.478538513184,38.6091270446777,108.181083679199,...,36591.234375,29120.5,35.6729278564453,41.5706977844238,183.897964477539,15.2200040817261,43.9895248413086,15.6228685379028,FSHD,FSHD
"""GSM121380""",2004.44140625,323.534271240234,306.088348388672,2756.24755859375,155.048233032227,1464.27734375,467.977722167969,207.292587280273,147.535690307617,67.3973159790039,...,36616.875,20877.6875,20.3714637756348,15.0363607406616,25.3939971923828,23.1137027740479,13.5756044387817,19.4236545562744,JDM,JDM
"""GSM74241""",2058.33154296875,476.876739501953,233.067993164062,2816.37841796875,99.692138671875,653.934692382812,280.965087890625,251.758575439453,46.3511352539062,204.119140625,...,10012.01171875,18654.59765625,26.7110958099365,18.0695552825928,33.9032745361328,6.36603403091431,29.4277782440186,10.9492521286011,ALS,ALS
"""GSM121364""",1350.91259765625,297.968414306641,760.519409179688,5822.83837890625,370.539611816406,827.995422363281,463.430206298828,314.118408203125,32.5820655822754,289.922210693359,...,37904.17578125,30788.791015625,41.0932960510254,49.871223449707,132.822799682617,47.035270690918,21.0585269927979,18.5991992950439,FSHD,FSHD
"""GSM121394""",2779.82080078125,191.995513916016,413.729187011719,2272.43579101562,106.888854980469,984.302062988281,472.243438720703,390.536956787109,24.6960868835449,116.159843444824,...,20614.07421875,18327.6953125,14.4564208984375,17.5908832550049,62.6825332641602,2.94605016708374,40.2984161376953,8.89613914489746,JDM,JDM
"""GSM74397""",3498.095703125,265.897766113281,420.10595703125,2899.826171875,198.020294189453,881.198425292969,452.184204101562,344.220489501953,52.3014373779297,120.586540222168,...,68765.9296875,67063.9921875,55.7100791931152,103.173957824707,198.71614074707,13.8588991165161,12.9839811325073,15.4652051925659,LGMD2I,Control
"""GSM121399""",1854.69946289062,176.634094238281,224.363571166992,2219.3681640625,82.6059875488281,1711.20739746094,442.881408691406,336.195465087891,479.007781982422,86.310920715332,...,24775.755859375,16098.21484375,22.118444442749,24.3609809875488,36.2432670593262,9.87153816223145,49.6119155883789,11.166467666626,JDM,JDM
"""GSM121384""",1769.32824707031,374.630065917969,436.080902099609,2860.84423828125,75.3084106445312,1413.05065917969,421.942810058594,100.77815246582,1975.64294433594,165.26106262207,...,22838.060546875,14500.080078125,22.9257659912109,27.5993709564209,49.767333984375,44.6158790588379,66.9496688842773,11.5374841690063,JDM,JDM
"""GSM74408""",1645.537109375,227.950881958008,83.3481216430664,3679.17529296875,208.619827270508,854.743896484375,344.861541748047,120.678092956543,38.5009994506836,266.104217529297,...,68963.84375,59634.78125,33.6149482727051,27.7216205596924,80.9148330688477,50.4332275390625,26.8753223419189,16.4285640716553,Control,Control
"""GSM74403""",1167.10241699219,213.26481628418,698.612243652344,2886.41748046875,179.3544921875,876.707824707031,549.297302246094,57.1866073608398,134.784530639648,245.170837402344,...,102131.34375,78111.6484375,38.3378524780273,169.8759765625,155.162368774414,82.2088775634766,73.1908950805664,22.4585800170898,Control,Control
"""GSM121393""",3429.96118164062,253.215911865234,185.197570800781,3079.16333007812,179.992584228516,2789.40942382812,1244.08801269531,260.788543701172,666.951171875,131.281845092773,...,68159.6796875,51291.796875,32.7221260070801,58.5433692932129,95.1865310668945,88.5610733032227,154.129364013672,19.6987724304199,JDM,JDM
"""GSM74358""",2410.77978515625,211.860015869141,360.752288818359,4502.60888671875,134.542861938477,548.727905273438,491.900390625,174.647247314453,31.5757808685303,234.022216796875,...,38223.390625,33364.1171875,23.9801845550537,23.0642795562744,11.6336336135864,16.1567630767822,22.106782913208,11.0143184661865,Control,Control
"""GSM121383""",1715.42700195312,456.252136230469,245.346755981445,2742.341796875,157.725067138672,1307.01330566406,553.392333984375,231.550842285156,184.94319152832,91.1431579589844,...,33181.92578125,20910.20703125,15.4731798171997,19.66330909729,46.4847679138184,9.60401725769043,20.0429058074951,13.6914720535278,JDM,JDM
"""GSM121389""",2933.95043945312,349.110748291016,340.968078613281,3041.04052734375,176.687438964844,1677.27465820312,1232.37768554688,56.5968589782715,300.121185302734,222.776824951172,...,32109.94140625,22910.275390625,28.717004776001,26.8340435028076,65.8823089599609,12.2493228912354,16.7852439880371,15.6936264038086,JDM,JDM
"""GSM74414""",2105.31665039062,472.844757080078,322.560699462891,2177.37915039062,160.083190917969,530.086853027344,382.684539794922,42.5707550048828,326.211669921875,136.413299560547,...,41121.71484375,31423.22265625,23.8311710357666,32.9236793518066,54.687068939209,8.63729095458984,24.208438873291,18.5218200683594,AQM,DMD

In [105]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
accuracy = float(cm.diagonal().sum())/len(Y_test)
print("\nAccuracy Of SVM For The Given Dataset : ", accuracy)

Accuracy Of SVM For The Given Dataset :  0.68